[versions]
kotlin = "2.2.21"
spring-boot = "4.0.1"
junit = "6.0.1"
rest-assured = "6.0.0"
okhttp = "5.3.2"
opentelemetry = "1.59.0"
opentelemetry-agent = "2.25.0"
embedded-postgres = "2.2.0"

[libraries]
spring-boot-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-starter-actuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-data-jpa-test = { module = "org.springframework.boot:spring-boot-starter-data-jpa-test" }
spring-boot-starter-webmvc = { module = "org.springframework.boot:spring-boot-starter-webmvc" }
spring-boot-starter-webmvc-test = { module = "org.springframework.boot:spring-boot-starter-webmvc-test" }
spring-boot-resttestclient = { module = "org.springframework.boot:spring-boot-resttestclient" }
spring-boot-webtestclient = { module = "org.springframework.boot:spring-boot-webtestclient" }
rest-assured = { module = "io.rest-assured:rest-assured", version.ref = "rest-assured" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
embedded-postgres = { module = "io.zonky.test:embedded-postgres", version.ref = "embedded-postgres" }
h2 = { module = "com.h2database:h2" }
jackson-module-kotlin = { module = "tools.jackson.module:jackson-module-kotlin" }
opentelemetry-api = { module = "io.opentelemetry:opentelemetry-api", version.ref = "opentelemetry" }
opentelemetry-javaagent = { module = "io.opentelemetry.javaagent:opentelemetry-javaagent", version.ref = "opentelemetry-agent" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
